import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      link: { type: 'doc', id: 'getting-started/introduction' },
      items: [
        'getting-started/create-a-document',
        'getting-started/create-a-blog-post',
        'getting-started/markdown-features',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      link: { type: 'doc', id: 'tutorial-extras/manage-docs-versions' },
      items: [
        'tutorial-extras/translate-your-site',
        'tutorial-extras/manage-docs-versions',
      ],
    },
  ],
};

export default sidebars;
