/*
 Copyright 2024 Qiniu Cloud (qiniu.com).

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

package linters

import (
	"testing"

	"github.com/google/go-github/v57/github"
)

func TestFormatStaticcheckLine(t *testing.T) {
	tc := []struct {
		input    string
		expected *LinterOutput
	}{
		{"cdn-admin.v2/client/dns/dnsapi.go:59:3: assignment to err", &LinterOutput{
			File:    "cdn-admin.v2/client/dns/dnsapi.go",
			Line:    59,
			Column:  3,
			Message: "assignment to err",
		}},
		{"smart_scheduler/provider_scheduler/provider_manager/provider_manager.go:207:31: should use make([]float64, len(result.CDNLog.Points)) instead (S1019)", &LinterOutput{
			File:    "smart_scheduler/provider_scheduler/provider_manager/provider_manager.go",
			Line:    207,
			Column:  31,
			Message: "should use make([]float64, len(result.CDNLog.Points)) instead (S1019)",
		}},
		{"cdn-admin.v2/api/api_line.go:342:3: should replace loop with ret = append(ret, scope.EdgeNodes...) (S1011)", &LinterOutput{
			File:    "cdn-admin.v2/api/api_line.go",
			Line:    342,
			Column:  3,
			Message: "should replace loop with ret = append(ret, scope.EdgeNodes...) (S1011)",
		}},
		{"cdn-admin.v2/api/api_line.go:342 should replace loop with ret = append(ret, scope.EdgeNodes...)", nil},
	}

	for _, c := range tc {
		output, err := GeneralLineParser(c.input)
		if output == nil {
			if c.expected != nil {
				t.Errorf("expected: %v, got: %v", c.expected, output)
			}
			continue
		}

		if c.expected == nil && output != nil {
			t.Errorf("expected error, got: %v", output)
		}

		if err != nil {
			t.Errorf("unexpected error: %v", err)
		}
		if output.File != c.expected.File || output.Line != c.expected.Line || output.Column != c.expected.Column || output.Message != c.expected.Message {
			t.Errorf("expected: %v, got: %v", c.expected, output)
		}
	}
}

func TestIsEmpty(t *testing.T) {
	tcs := []struct {
		input    []string
		expected bool
	}{
		{[]string{}, true},
		{[]string{""}, true},
		{[]string{" "}, false},
		{[]string{"a"}, false},
	}
	for _, tc := range tcs {
		actual := IsEmpty(tc.input...)
		if actual != tc.expected {
			t.Errorf("expected: %v, got: %v", tc.expected, actual)
		}
	}
}

func TestFilters(t *testing.T) {
	tcs := []struct {
		name        string
		a           Agent
		input       map[string][]LinterOutput
		expected    map[string][]LinterOutput
		expectedErr error
	}{
		{
			name: "filterByPRChanged",
			a: Agent{
				PullRequestChangedFiles: []*github.CommitFile{
					{
						Filename: github.String("pkg/apis/xxx_1.go"),
						Patch:    github.String(`@@ -2,7 +1,7 @@`),
					},
					{
						Filename: github.String(".testdata/xxx_1.go"),
						Patch:    github.String(`@@ -1,7 +1,7 @@`),
					},
				},
			},
			input: map[string][]LinterOutput{
				".testdata/xxx_1.go": {
					{
						Line:    4,
						Column:  16,
						Message: `abc`,
					},
				},
			},
			expected: map[string][]LinterOutput{
				".testdata/xxx_1.go": {
					{
						Line:    4,
						Column:  16,
						Message: `abc`,
					},
				},
			},
			expectedErr: nil,
		},
		{
			name: "filterByAutoGenerated",
			a: Agent{
				PullRequestChangedFiles: []*github.CommitFile{
					{
						Filename: github.String(".testdata/auto.go"),
						Patch:    github.String(`@@ -1,7 +1,7 @@`),
					},
					{
						Filename: github.String("pkg/apis/xxx_2.go"),
						Patch:    github.String(`@@ -1,7 +1,7 @@`),
					},
				},
			},
			input: map[string][]LinterOutput{
				".testdata/autogen.go": {
					{
						Line:    4,
						Column:  16,
						Message: `unknown JSON option "default=abc" (SA5008)`,
					},
				},
			},
			expected:    map[string][]LinterOutput{},
			expectedErr: nil,
		},
		{
			name: "normalCase",
			a: Agent{
				PullRequestChangedFiles: []*github.CommitFile{
					{
						Filename: github.String(".testdata/xxx_1.go"),
						Patch:    github.String(`@@ -1,7 +1,7 @@`),
					},
				},
			},
			input: map[string][]LinterOutput{
				".testdata/xxx_1.go": {
					{
						Line:    4,
						Column:  16,
						Message: `err not used`,
					},
				},
			},
			expected: map[string][]LinterOutput{
				".testdata/xxx_1.go": {
					{
						Line:    4,
						Column:  16,
						Message: `err not used`,
					},
				},
			},
			expectedErr: nil,
		},
		{
			name: "filterByNotInHunk",
			a: Agent{
				PullRequestChangedFiles: []*github.CommitFile{
					{
						Filename: github.String("pkg/apis/xxx_2.go"),
						Patch:    github.String(`@@ -1,3 +1,3 @@`),
					},
				},
			},
			input: map[string][]LinterOutput{
				"pkg/apis/xxx_2.go": {
					{
						Line:    4,
						Column:  16,
						Message: `err not used`,
					},
				},
			},
			expected:    map[string][]LinterOutput{},
			expectedErr: nil,
		},
	}

	for _, tc := range tcs {
		t.Run(tc.name, func(t *testing.T) {
			results, err := Filters(nil, tc.a, tc.input)
			if err != tc.expectedErr {
				t.Errorf("expected error %v, got %v", tc.expectedErr, err)
			}
			if len(results) != len(tc.expected) {
				t.Errorf("expected %v, got %v", tc.expected, results)
			}
			for file, linterResults := range results {
				if len(linterResults) != len(tc.expected[file]) {
					t.Errorf("expected %v, got %v", tc.expected[file], linterResults)
				}
				for i, linter := range linterResults {
					if linter.Line != tc.expected[file][i].Line {
						t.Errorf("expected %v, got %v", tc.expected[file][i].Line, linter.Line)
					}
					if linter.Column != tc.expected[file][i].Column {
						t.Errorf("expected %v, got %v", tc.expected[file][i].Column, linter.Column)
					}
					if linter.Message != tc.expected[file][i].Message {
						t.Errorf("expected %v, got %v", tc.expected[file][i].Message, linter.Message)
					}
				}
			}
		})
	}
}
